version: '3.4'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: java -jar app.jar
    ports:
      - "8080:8080"
    volumes:
      - .:/app:Z
    networks:
      - backend
    environment: &environment-web
      DB_ENGINE: django.db.backends.postgresql
      DB_HOST: db
      DB_NAME: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
      DB_USER: postgres
      CACHES_LOCATION: cache:11211
    stdin_open: true
    tty: true

networks:
  backend: { }
