version: '3.4'

services:
  web:
    image: shaifulali/automation-java:${IMAGE_TAG}
    depends_on:
      - postgres
    volumes:
      - .:/app:Z
    networks:
      - backend
      - nginx
    environment: &environment-web
      DATA_SOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      DATA_SOURCE_HOST: postgres
      DATA_SOURCE_NAME: postgres
      DATA_SOURCE_PASSWORD: automation
      DATA_SOURCE_PORT: 5432
      DATA_SOURCE_USER: automation
      CACHES_LOCATION: cache:11211
      VIRTUAL_PORT: 8000
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${VIRTUAL_HOST}

  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_PASSWORD: automation
      POSTGRES_DB: postgres
      POSTGRES_USER: automation
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend: { }
  nginx:
    external:
      name: nginx_default

volumes:
  postgres_data: