name: deploy-to-remote-server

on:
  push:
    branches:
      - "*"

jobs:
  docker-build:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate Docker Compose file
        run: docker-compose config --quiet

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker Image to Docker Hub
        run: |
          docker build -t ${{ secrets.DOCKERHUB_REPO }}:${GITHUB_REF#refs/heads/} .
          docker push ${{ secrets.DOCKERHUB_REPO }}:${GITHUB_REF#refs/heads/}
          docker logout


      - name: Set TAG variable
        run: |
          export TAG=${GITHUB_REF#refs/heads/}
          echo "IMAGE_TAG=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          echo "VIRTUAL_HOST=${GITHUB_REF#refs/heads/}.sislam.info" >> $GITHUB_ENV
          echo "url=http://$VIRTUAL_HOST" >> $GITHUB_ENV
          echo "on_stop=stop" >> $GITHUB_ENV

      - name: Deploy Using docker stack
        run: |
          eval $(ssh-agent -s)
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -
          install -m 0700 -d ~/.ssh
          ssh-keyscan ${{ secrets.SSH_SERVER }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          unset DOCKER_HOST
          docker context create tmp --docker "host=ssh://${{ secrets.SSH_USER }}@${{ secrets.SSH_SERVER }}"
          docker context use tmp
          docker stack deploy --with-registry-auth --compose-file docker-stack.yml auto_$IMAGE_TAG


