name: Pipeline for removing docker stack on branch deletion

on:
  delete:
    branches:
      - '*'

jobs:
  job_on_branch_deletion:
    runs-on: ubuntu-latest
    if: github.event_name == 'delete' && github.event.ref_type == 'branch'

    steps:
      - name: Set Image TAG
        run: |
          echo "IMAGE_TAG=${{ github.event.ref }}" >> $GITHUB_ENV

      - name: Delete Branch deployment
        run: |
          eval $(ssh-agent -s)
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -
          install -m 0700 -d ~/.ssh
          ssh-keyscan ${{ secrets.SSH_SERVER }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          unset DOCKER_HOST
          docker context create tmp --docker "host=ssh://${{ secrets.SSH_USER }}@${{ secrets.SSH_SERVER }}"
          docker context use tmp
          docker stack rm auto_$IMAGE_TAG
